title: Gabriel Barbir
description: Cybersecurity writeups focused on detection engineering, threat hunting, and offensive security.
url: https://zero-for683.github.io

minimal_mistakes_skin: dark


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

masthead_title: "Gabriel Barbir"
breadcrumbs: true

header:
  nav: true

navigation:
  - title: "Writeups"
    url: /categories/
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
