title: Gabriel Barbir
description: Cybersecurity writeups focused on detection engineering, threat hunting, and offensive security.
url: https://zero-for683.github.io

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

masthead_title: "Gabriel"
breadcrumbs: true

# Enable header nav and point it at the "main" menu below
header:
  nav: main


author:
  name: "Gabriel Barbir"
  bio: "Cybersecurity Analyst â€¢ OSCP"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/gabriel-barbir/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ZeroFor-683"



